(()=>{'use strict';
const CSV='https://docs.google.com/spreadsheets/d/e/2PACX-1vR8fVHg088VLKufg9U-p5R0YrI2ab0eHOCBe2Yx48v3bf4tIemOdpsmxihi786cAYC_gJZOtmpqLXQK/pub?output=csv';
const GVIZ='https://docs.google.com/spreadsheets/d/e/2PACX-1vR8fVHg088VLKufg9U-p5R0YrI2ab0eHOCBe2Yx48v3bf4tIemOdpsmxihi786cAYC_gJZOtmpqLXQK/gviz/tq';
const ARC='https://services.arcgis.com/hkQNLKNeDVYBjvFE/arcgis/rest/services/senderos/FeatureServer/2/query';
const OFFICIAL='https://www.senderosdelapalma.es/senderos/estado-de-los-senderos/',CATALOG='https://www.senderosdelapalma.es/listado-de-senderos/',CACHE='lp-trails-v4';
const K={open:'#25a55b',partial:'#e3a328',closed:'#d8493f',unknown:'#8a938e'};
const I={ru:{all:'Все',open:'Открыты',partial:'Ограничения',closed:'Закрыты',unknown:'Неизвестно',routes:'Маршруты',search:'Маршрут: PR LP 5.1, GR 131…',updated:'Обновлено',loading:'Загрузка официальных данных…',stale:'Не удалось получить свежие данные. Показана последняя сохранённая версия.',source:'Источник: Red de Senderos de La Palma / Cabildo de La Palma',notice:'Официальное примечание',none:'Примечаний нет.',distance:'Длина',difficulty:'Сложность',official:'Официальный статус',catalog:'Каталог маршрутов',google:'Google Maps',nogeo:'нет линии на официальной карте',openS:'Открыт',partialS:'Ограничения / частично открыт',closedS:'Закрыт',unknownS:'Статус неизвестен',unofficial:'Неофициальный просмотрщик официальных данных. Проверяйте время обновления перед выходом.'},es:{all:'Todos',open:'Abiertos',partial:'Restricciones',closed:'Cerrados',unknown:'Desconocido',routes:'Senderos',search:'Sendero: PR LP 5.1, GR 131…',updated:'Actualizado',loading:'Cargando datos oficiales…',stale:'No se pudieron obtener datos nuevos. Se muestra la última copia guardada.',source:'Fuente: Red de Senderos de La Palma / Cabildo de La Palma',notice:'Aviso oficial',none:'Sin avisos.',distance:'Longitud',difficulty:'Dificultad',official:'Estado oficial',catalog:'Listado de senderos',google:'Google Maps',nogeo:'sin línea en el mapa oficial',openS:'Abierto',partialS:'Restricciones / parcialmente abierto',closedS:'Cerrado',unknownS:'Estado desconocido',unofficial:'Visor no oficial de datos oficiales. Comprueba la hora de actualización antes de salir.'}};
const $=x=>document.getElementById(x);let lang='ru',filter='all',q='',trails=[],selected=null,updated=null,stale=false,layers=[];
const t=k=>I[lang][k]||k,norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/\s+/g,' ').trim(),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
if(!window.L){document.body.innerHTML='<div style="padding:20px;font-family:system-ui">Map library failed to load. Reload the page.</div>';return}
const map=L.map('map',{zoomControl:false}).setView([28.67,-17.86],11);L.control.zoom({position:'bottomright'}).addTo(map);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© OpenStreetMap'}).addTo(map);
function csv(text){const rows=[];let r=[],f='',qq=false;for(let i=0;i<text.length;i++){const c=text[i];if(qq){if(c==='"'){if(text[i+1]==='"'){f+='"';i++}else qq=false}else f+=c}else if(c==='"')qq=true;else if(c===','){r.push(f);f=''}else if(c==='\n'||c==='\r'){if(c==='\r'&&text[i+1]==='\n')i++;r.push(f);f='';if(r.some(x=>x.trim()))rows.push(r);r=[]}else f+=c}if(f||r.length){r.push(f);rows.push(r)}if(!rows.length)return[];const h=rows.shift().map(x=>x.trim());return rows.map(a=>Object.fromEntries(h.map((k,i)=>[k,a[i]||''])))} 
function gvizRows(x){const h=(x?.table?.cols||[]).map(c=>c.label||c.id||'');return(x?.table?.rows||[]).map(r=>Object.fromEntries(h.map((k,i)=>[k,r.c?.[i]?.v??''])))}
function pick(o,a){for(const n of a)if(Object.prototype.hasOwnProperty.call(o,n))return o[n];for(const n of a){const nn=norm(n),k=Object.keys(o).find(x=>norm(x)===nn);if(k)return o[k]}return''}
function clean(s){return String(s||'').replace(/<[^>]*>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/\s+/g,' ').trim()}
function keyName(name){const n=norm(name);let m=n.match(/\bGR\s*[- ]?\s*(130|131)\b.*?(?:ETAPA|STAGE)?\s*(\d{1,2})\b/);if(m)return'GR'+m[1]+'-'+parseInt(m[2]);m=n.match(/\bPR\s*[- ]?\s*LP\s*[- ]?\s*0?(\d{1,2})(?:\s*[.\-]\s*0?(\d{1,2}))?/);if(m)return'PRLP-'+parseInt(m[1])+(m[2]?'.'+parseInt(m[2]):'');m=n.match(/\bSL\s*[- ]?\s*([A-Z]{2})\s*[- ]?\s*0?(\d{1,3})/);return m?'SL-'+m[1]+'-'+parseInt(m[2]):null}
function keyArc(id){const s=norm(id).replace(/[^A-Z0-9]/g,'');let m=s.match(/^GR(130|131)(\d{1,2})$/);if(m)return'GR'+m[1]+'-'+parseInt(m[2]);m=s.match(/^PRLP(\d{2})(\d)(\d)$/);if(m){const a=parseInt(m[1]),b=parseInt(m[2]);return'PRLP-'+a+(b?'.'+b:'')}m=s.match(/^PRLP0?(\d{1,2})$/);return m?'PRLP-'+parseInt(m[1]):null}
function code(k){if(!k)return'—';let m=k.match(/^GR(130|131)-(\d+)$/);if(m)return'GR '+m[1]+' · '+m[2];m=k.match(/^PRLP-(\d+)(?:\.(\d+))?$/);if(m)return'PR LP '+String(m[1]).padStart(2,'0')+(m[2]?'.'+m[2]:'');m=k.match(/^SL-([A-Z]{2})-(\d+)$/);return m?'SL '+m[1]+' '+m[2]:k}
function yes(v){return/^(SI|SÍ|YES|TRUE|1|X)$/i.test(String(v||'').trim())}
function state(e,a,alert){if(alert)return'closed';e=norm(e);a=norm(a);if(e.includes('CERRAD')||e.includes('CLOSED'))return'closed';if(e.includes('PARCIAL')||e.includes('RESTRIC'))return'partial';if(e.includes('ABIERT')||e.includes('OPEN'))return /\b(CERRAD|CIERR|CORTAD|TRAMO|DESVIO|RESTRIC|OBRAS|PROHIB|AFECTAD)\b/.test(a)?'partial':'open';return'unknown'}
function esriGeo(j){return{features:(j.features||[]).map(f=>({type:'Feature',properties:f.attributes||{},geometry:{type:'MultiLineString',coordinates:(f.geometry?.paths||[]).map(p=>p.map(x=>[x[0],x[1]]))}}))}}
function build(rows,geo){const m=new Map;for(const r of rows){const name=clean(pick(r,['Nombre_ES','Nombre ES','Nombre','Sendero'])),k=keyName(name),st=clean(pick(r,['Estado_ES','Estado ES','Estado'])),note=clean(pick(r,['Aviso_ES','Aviso ES','Aviso'])),al=yes(pick(r,['Cierre por Alerta','Cierre_por_Alerta','Alerta'])),id=k||'CSV-'+m.size;m.set(id,{key:id,code:code(k),name:name||code(k),status:state(st,note,al),note,geom:null,distance:null,difficulty:'',arcId:null})}for(const f of geo.features||[]){const aid=f.properties?.ID||'',k=keyArc(aid);let tr=k?m.get(k):null;if(!tr){const id=k||'ARC-'+(aid||m.size);tr={key:id,code:code(k)||aid||'—',name:aid||code(k)||'Sendero',status:'unknown',note:'',geom:null,distance:null,difficulty:'',arcId:aid};m.set(id,tr)}tr.geom=f.geometry;const d=parseFloat(String(f.properties?.LONGITUD??f.properties?.LONG??'').replace(',','.'));tr.distance=Number.isFinite(d)?d:null;tr.difficulty=clean(f.properties?.DIFICULTAD||'');tr.arcId=aid}return[...m.values()]}
function fetchT(url,ms=10000){const c=new AbortController,id=setTimeout(()=>c.abort(),ms);return fetch(url,{cache:'no-store',signal:c.signal}).finally(()=>clearTimeout(id))}
function jsonp(url,param='callback',ms=10000){return new Promise((res,rej)=>{const cb='__lp'+Date.now()+Math.random().toString(36).slice(2),s=document.createElement('script'),to=setTimeout(()=>done(new Error('timeout')),ms);function done(e,v){clearTimeout(to);try{delete window[cb]}catch(_){}s.remove();e?rej(e):res(v)}window[cb]=v=>done(null,v);s.onerror=()=>done(new Error('script'));s.src=url+(url.includes('?')?'&':'?')+encodeURIComponent(param)+'='+encodeURIComponent(cb);document.head.appendChild(s)})}
function gviz(ms=10000){return new Promise((res,rej)=>{const cb='__g'+Date.now()+Math.random().toString(36).slice(2),s=document.createElement('script'),to=setTimeout(()=>done(new Error('timeout')),ms);function done(e,v){clearTimeout(to);try{delete window[cb]}catch(_){}s.remove();e?rej(e):res(v)}window[cb]=v=>done(null,v);s.onerror=()=>done(new Error('script'));s.src=GVIZ+'?tqx='+encodeURIComponent('out:json;responseHandler:'+cb)+'&_='+Date.now();document.head.appendChild(s)})}
async function getRows(){try{const r=await fetchT(CSV+'&_='+Date.now());if(!r.ok)throw 0;const a=csv(await r.text());if(!a.length)throw 0;return a}catch(_){const a=gvizRows(await gviz());if(!a.length)throw 0;return a}}
async function getGeo(){const p='?where=1%3D1&outFields=*&outSR=4326&geometryPrecision=5&f=geojson&_='+Date.now();try{const r=await fetchT(ARC+p);if(!r.ok)throw 0;const g=await r.json();if(!Array.isArray(g.features))throw 0;return g}catch(_){return esriGeo(await jsonp(ARC+'?where=1%3D1&outFields=*&outSR=4326&geometryPrecision=5&returnGeometry=true&f=json&_='+Date.now()))}}
async function load(){const b=$('refresh');b.textContent='…';$('status').textContent=t('loading');$('notice').className='notice';try{const a=await Promise.all([getRows(),getGeo()]);trails=build(a[0],a[1]);if(!trails.length)throw 0;updated=new Date().toISOString();stale=false;try{localStorage.setItem(CACHE,JSON.stringify({updated,trails}))}catch(_){}render();fit()}catch(e){let c=null;try{c=JSON.parse(localStorage.getItem(CACHE)||'null')}catch(_){}if(c?.trails?.length){trails=c.trails;updated=c.updated;stale=true;render();fit()}else{stale=true;$('status').textContent=t('stale');$('notice').textContent=t('stale');$('notice').className='notice show warn'}}finally{b.textContent='↻'}}
function visible(){const qq=norm(q);return trails.filter(x=>(filter==='all'||x.status===filter)&&(!qq||norm(x.code+' '+x.name+' '+(x.arcId||'')).includes(qq)))}function counts(){return trails.reduce((a,x)=>(a[x.status]=(a[x.status]||0)+1,a),{open:0,partial:0,closed:0,unknown:0})}function label(s){return s==='open'?t('openS'):s==='partial'?t('partialS'):s==='closed'?t('closedS'):t('unknownS')}
function clearLayers(){layers.forEach(x=>map.removeLayer(x));layers=[]}function draw(){clearLayers();for(const tr of visible()){if(!tr.geom)continue;const l=L.geoJSON({type:'Feature',properties:{},geometry:tr.geom},{style:{color:K[tr.status]||K.unknown,weight:tr.key===selected?8:5,opacity:tr.status==='unknown'?.68:.96},onEachFeature:(_,layer)=>layer.on('click',()=>select(tr.key,false))}).addTo(map);layers.push(l)}}function fit(){const vs=visible().filter(x=>x.geom);if(!vs.length)return;let b=null;for(const x of vs){const z=L.geoJSON({type:'Feature',properties:{},geometry:x.geom}).getBounds();b=b?b.extend(z):z}if(b?.isValid())map.fitBounds(b.pad(.04),{paddingTopLeft:[20,145],paddingBottomRight:[20,90],maxZoom:13})}
function render(){const c=counts();$('filters').innerHTML=[['all',t('all'),trails.length,null],['open',t('open'),c.open,K.open],['partial',t('partial'),c.partial,K.partial],['closed',t('closed'),c.closed,K.closed]].map(x=>'<button class="chip '+(filter===x[0]?'active':'')+'" data-f="'+x[0]+'">'+(x[3]?'<span class="dot" style="background:'+x[3]+'"></span>':'')+x[1]+' '+x[2]+'</button>').join('');$('filters').querySelectorAll('button').forEach(b=>b.onclick=()=>{filter=b.dataset.f;selected=null;closeCard();render();fit()});$('legend').innerHTML='<div><span class="line" style="background:'+K.open+'"></span>'+t('open')+'</div><div><span class="line" style="background:'+K.partial+'"></span>'+t('partial')+'</div><div><span class="line" style="background:'+K.closed+'"></span>'+t('closed')+'</div><div><span class="line" style="background:'+K.unknown+'"></span>'+t('unknown')+'</div>';$('search').placeholder=t('search');$('lang').textContent=lang.toUpperCase();$('openList').textContent=t('routes')+' · '+visible().length;$('drawerTitle').textContent=t('routes');$('routes').innerHTML=visible().map(x=>'<button class="route" data-k="'+esc(x.key)+'"><span class="dot" style="background:'+K[x.status]+'"></span><span class="route-main"><span class="route-code">'+esc(x.code)+'</span><span class="route-name">'+esc(x.name)+'</span></span>'+(x.geom?'':'<span class="nogeo">'+t('nogeo')+'</span>')+'</button>').join('');$('routes').querySelectorAll('button').forEach(b=>b.onclick=()=>select(b.dataset.k,true));if(updated)$('status').textContent=t('updated')+': '+new Date(updated).toLocaleString(lang==='ru'?'ru-RU':'es-ES',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})+' · '+t('source');if(stale){$('notice').textContent=t('stale');$('notice').className='notice show warn'}draw();if(selected){const x=trails.find(y=>y.key===selected);if(x)card(x)}}
function google(tr){try{const c=L.geoJSON({type:'Feature',properties:{},geometry:tr.geom}).getBounds().getCenter();return'https://www.google.com/maps/search/?api=1&query='+c.lat+','+c.lng}catch(_){return'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(tr.name+' La Palma')}}
function select(k,doFit){selected=k;const tr=trails.find(x=>x.key===k);if(!tr)return;$('drawer').classList.remove('show');$('openList').style.display='none';card(tr);draw();if(doFit&&tr.geom){const b=L.geoJSON({type:'Feature',properties:{},geometry:tr.geom}).getBounds();if(b.isValid())map.fitBounds(b,{paddingTopLeft:[20,150],paddingBottomRight:[20,250],maxZoom:15})}}
function card(tr){$('card').innerHTML='<div class="card-head"><div class="card-title"><div class="card-code">'+esc(tr.code)+'</div>'+esc(tr.name)+'</div><button id="closeCard" class="close">×</button></div><div class="badge"><span class="dot" style="background:'+K[tr.status]+'"></span>'+esc(label(tr.status))+'</div><div class="facts"><div class="fact"><b>'+t('distance')+'</b>'+(tr.distance==null?'—':tr.distance.toFixed(1)+' km')+'</div><div class="fact"><b>'+t('difficulty')+'</b>'+esc(tr.difficulty||'—')+'</div></div><div class="official-note"><b>'+t('notice')+'</b>'+esc(tr.note||t('none'))+'</div><div class="actions"><a class="link primary" href="'+OFFICIAL+'" target="_blank" rel="noopener">'+t('official')+' ↗</a><a class="link" href="'+CATALOG+'" target="_blank" rel="noopener">'+t('catalog')+' ↗</a><a class="link" href="'+google(tr)+'" target="_blank" rel="noopener">'+t('google')+' ↗</a></div><div class="disclaimer">'+t('unofficial')+'</div>';$('card').classList.add('show');$('closeCard').onclick=closeCard}
function closeCard(){selected=null;$('card').classList.remove('show');$('openList').style.display='block';draw()}
$('search').oninput=e=>{q=e.target.value;selected=null;closeCard();render();fit()};$('refresh').onclick=load;$('lang').onclick=()=>{lang=lang==='ru'?'es':'ru';render()};$('openList').onclick=()=>{$('drawer').classList.add('show');$('openList').style.display='none'};$('closeDrawer').onclick=()=>{$('drawer').classList.remove('show');$('openList').style.display='block'};
render();load();
})();